// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace SipgateFaxdrucker.SipgateAPI.Models
{
    public partial class EndpointResponse
    {
        /// <summary>
        /// Initializes a new instance of the EndpointResponse class.
        /// </summary>
        public EndpointResponse() { }

        /// <summary>
        /// Initializes a new instance of the EndpointResponse class.
        /// </summary>
        public EndpointResponse(string extension = default, string type = default)
        {
            Extension = extension;
            Type = type;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extension")]
        public string Extension { get; set; }

        /// <summary>
        /// Possible values include: 'SMS', 'REGISTER', 'EXTERNAL', 'FAX',
        /// 'MOBILE', 'GROUP', 'VOICEMAIL', 'PHONELINE', 'USER'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
