// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace SipgateFaxdrucker.SipgateAPI.Models
{
    public partial class GroupFaxlineResponse
    {
        /// <summary>
        /// Initializes a new instance of the GroupFaxlineResponse class.
        /// </summary>
        public GroupFaxlineResponse() { }

        /// <summary>
        /// Initializes a new instance of the GroupFaxlineResponse class.
        /// </summary>
        public GroupFaxlineResponse(string id = default, string alias = default, string tagline = default, bool? canSend = default, bool? canReceive = default, string groupId = default)
        {
            Id = id;
            Alias = alias;
            Tagline = tagline;
            CanSend = canSend;
            CanReceive = canReceive;
            GroupId = groupId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alias")]
        public string Alias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tagline")]
        public string Tagline { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canSend")]
        public bool? CanSend { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canReceive")]
        public bool? CanReceive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public string GroupId { get; set; }

    }
}
