// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace SipgateFaxdrucker.SipgateAPI.Models
{
    public partial class RoutedEndpointResponse
    {
        /// <summary>
        /// Initializes a new instance of the RoutedEndpointResponse class.
        /// </summary>
        public RoutedEndpointResponse() { }

        /// <summary>
        /// Initializes a new instance of the RoutedEndpointResponse class.
        /// </summary>
        public RoutedEndpointResponse(string type = default, EndpointResponse endpoint = default)
        {
            Type = type;
            Endpoint = endpoint;
        }

        /// <summary>
        /// Possible values include: 'FORWARDED', 'ROUTED', 'PICKUP'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpoint")]
        public EndpointResponse Endpoint { get; set; }

    }
}
