// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Net;
using Newtonsoft.Json;

namespace SipgateFaxdrucker.SipgateAPI.Models
{
    public partial class SendFaxSessionResponse
    {
        /// <summary>
        /// Initializes a new instance of the SendFaxSessionResponse class.
        /// </summary>
        public SendFaxSessionResponse() { }

        /// <summary>
        /// Initializes a new instance of the SendFaxSessionResponse class.
        /// </summary>
        public SendFaxSessionResponse(string sessionId = default, HttpStatusCode statusCode = default)
        {
            SessionId = sessionId;
            StatusCode = statusCode;
        }

        /// <summary>
        /// Initializes a new instance of the SendFaxSessionResponse class.
        /// </summary>
        public SendFaxSessionResponse(string sessionId = default)
        {
            SessionId = sessionId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sessionId")]
        public string SessionId { get; set; }


        ///<summary></summary>
        [JsonProperty(PropertyName = "statusCode")]
        public HttpStatusCode StatusCode { get; set; }
    }
}